<a href="https://colab.research.google.com/github/kl01abhinav2-coder/git_hub_1/blob/main/Case_Study_on_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy  as np
import pandas as pd

In [ ]:
house_priced=pd.read_csv("/content/House_Pricing.csv")
house_priced.head()

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,...,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7129300520,14 October 2017,221900.0,3,1.00,1180.0,5650.0,1.0,No,NaN,...,7,1180.0,0,63,0,98178.0,47.5112,-122.257,1340.0,5650
1,6414100192,14 December 2017,538000.0,3,2.25,2570.0,7242.0,2.0,No,NaN,...,7,2170.0,400,67,1991,98125.0,47.7210,-122.319,1690.0,7639
2,5631500400,15 February 2016,180000.0,2,1.00,770.0,10000.0,1.0,No,NaN,...,6,770.0,0,85,0,98028.0,47.7379,-122.233,2720.0,8062
3,2487200875,14 December 2017,604000.0,4,3.00,1960.0,5000.0,1.0,No,NaN,...,7,1050.0,910,53,0,98136.0,47.5208,-122.393,1360.0,5000
4,1954400510,15 February 2016,510000.0,3,2.00,1680.0,8080.0,1.0,No,NaN,...,8,1680.0,0,31,0,98074.0,47.6168,-122.045,1800.0,7503

In [ ]:
house_priced.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   ID                                         21613 non-null  int64
 1   Date House was Sold                        21613 non-null  object
 2   Sale Price                                 21609 non-null  float64
 3   No of Bedrooms                             21613 non-null  int64
 4   No of Bathrooms                            21609 non-null  float64
 5   Flat Area (in Sqft)                        21604 non-null  float64
 6   Lot Area (in Sqft)                         21604 non-null  float64
 7   No of Floors                               21613 non-null  float64
 8   Waterfront View                            21613 non-null  object
 9   No of Times Visited                        2124 non-null   object
 10  Condition of the House                     21613 non-null  object
 11  Overall Grade                              21613 non-null  int64
 12  Area of the House from Basement (in Sqft)  21610 non-null  float64
 13  Basement Area (in Sqft)                    21613 non-null  int64
 14  Age of House (in Years)                    21613 non-null  int64
 15  Renovated Year                             21613 non-null  int64
 16  Zipcode                                    21612 non-null  float64
 17  Latitude                                   21612 non-null  float64
 18  Longitude                                  21612 non-null  float64
 19  Living Area after Renovation (in Sqft)     21612 non-null  float64
 20  Lot Area after Renovation (in Sqft)        21613 non-null  int64
dtypes: float64(10), int64(7), object(4)
memory usage: 3.5+ MB

In [ ]:
house_priced.describe()

,ID,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
count,2.161300e+04,2.160900e+04,21613.000000,21609.000000,21604.000000,2.160400e+04,21613.000000,21613.000000,21610.000000,21613.000000,21613.000000,21613.000000,21612.000000,21612.000000,21612.000000,21612.000000,21613.000000
mean,4.580302e+09,5.401984e+05,3.370842,2.114732,2079.931772,1.510776e+04,1.494309,7.623467,1788.344193,291.509045,46.994864,84.402258,98077.937766,47.560048,-122.213892,1986.538914,12768.455652
std,2.876566e+09,3.673890e+05,0.930062,0.770138,918.487597,4.142827e+04,0.539989,1.105439,827.982604,442.575043,29.373411,401.679240,53.505425,0.138565,0.140830,685.404255,27304.179631
min,1.000102e+06,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,1.000000,290.000000,0.000000,3.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,2.123049e+09,3.219500e+05,3.000000,1.750000,1429.250000,5.040000e+03,1.000000,7.000000,1190.000000,0.000000,21.000000,0.000000,98033.000000,47.470975,-122.328000,1490.000000,5100.000000
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1910.000000,7.617500e+03,1.500000,7.000000,1560.000000,0.000000,43.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2550.000000,1.068825e+04,2.000000,8.000000,2210.000000,560.000000,67.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,9.900000e+09,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,10.000000,9410.000000,4820.000000,118.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

#Duplicate Removal

In [ ]:
duplicate_count=house_priced.duplicated().sum()
print("total number of duplicate rows are",duplicate_count)

total number of duplicate rows are 0

In [ ]:
duplicate_count=house_priced.T.duplicated()
print(duplicate_count)

ID                                           False
Date House was Sold                          False
Sale Price                                   False
No of Bedrooms                               False
No of Bathrooms                              False
Flat Area (in Sqft)                          False
Lot Area (in Sqft)                           False
No of Floors                                 False
Waterfront View                              False
No of Times Visited                          False
Condition of the House                       False
Overall Grade                                False
Area of the House from Basement (in Sqft)    False
Basement Area (in Sqft)                      False
Age of House (in Years)                      False
Renovated Year                               False
Zipcode                                      False
Latitude                                     False
Longitude                                    False
Living Area after Renovation (in Sqft)       False
Lot Area after Renovation (in Sqft)          False
dtype: bool

#Handling Missing Values

In [ ]:
column_missing_value=house_priced.isnull().sum()
print(column_missing_value)

ID                                               0
Date House was Sold                              0
Sale Price                                       4
No of Bedrooms                                   0
No of Bathrooms                                  4
Flat Area (in Sqft)                              9
Lot Area (in Sqft)                               9
No of Floors                                     0
Waterfront View                                  0
No of Times Visited                          19489
Condition of the House                           0
Overall Grade                                    0
Area of the House from Basement (in Sqft)        3
Basement Area (in Sqft)                          0
Age of House (in Years)                          0
Renovated Year                                   0
Zipcode                                          1
Latitude                                         1
Longitude                                        1
Living Area after Renovation (in Sqft)           1
Lot Area after Renovation (in Sqft)              0
dtype: int64

In [ ]:
numerical_values = house_priced.select_dtypes(include =["int64","float64"])
house_priced[numerical_values.columns] = numerical_values.fillna(numerical_values.median())
house_priced[numerical_values.columns].isnull().sum()

ID                                           0
Sale Price                                   0
No of Bedrooms                               0
No of Bathrooms                              0
Flat Area (in Sqft)                          0
Lot Area (in Sqft)                           0
No of Floors                                 0
Overall Grade                                0
Area of the House from Basement (in Sqft)    0
Basement Area (in Sqft)                      0
Age of House (in Years)                      0
Renovated Year                               0
Zipcode                                      0
Latitude                                     0
Longitude                                    0
Living Area after Renovation (in Sqft)       0
Lot Area after Renovation (in Sqft)          0
dtype: int64

In [ ]:
house_priced['No of Times Visited'] = house_priced['No of Times Visited'].fillna(house_priced['No of Times Visited'].mode()[0])
house_priced['No of Times Visited'].isnull().sum()

np.int64(0)

In [ ]:
cate_values = house_priced.select_dtypes(include =["object"])
house_priced[cate_values.columns] = cate_values.fillna(cate_values.mode())
house_priced[cate_values.columns].isnull().sum()

Date House was Sold       0
Waterfront View           0
No of Times Visited       0
Condition of the House    0
dtype: int64

#Outlier Removal

In [ ]:
num_cols = house_priced.select_dtypes(include=["int64", "float64"]).columns

outlier_summary = {}

for col in num_cols:
    Q1 = house_priced[col].quantile(0.25)
    Q3 = house_priced[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = house_priced[(house_priced [col] < lower_bound) | (house_priced [col] > upper_bound)]
    outlier_summary[col] = outliers.shape[0]

outlier_summary

{'ID': 0,
 'Sale Price': 1159,
 'No of Bedrooms': 546,
 'No of Bathrooms': 571,
 'Flat Area (in Sqft)': 572,
 'Lot Area (in Sqft)': 2423,
 'No of Floors': 0,
 'Overall Grade': 1911,
 'Area of the House from Basement (in Sqft)': 610,
 'Basement Area (in Sqft)': 496,
 'Age of House (in Years)': 0,
 'Renovated Year': 914,
 'Zipcode': 0,
 'Latitude': 2,
 'Longitude': 256,
 'Living Area after Renovation (in Sqft)': 544,
 'Lot Area after Renovation (in Sqft)': 2194}

In [ ]:
features_to_clean = [
    "Sale Price",
    "Flat Area (in Sqft)",
    "Lot Area (in Sqft)",
    "Living Area after Renovation (in Sqft)",
    "Lot Area after Renovation (in Sqft)"
]

# Apply IQR-based outlier removal
House_Pricing_cleaned = house_priced.copy()

for col in features_to_clean:
    Q1 = House_Pricing_cleaned[col].quantile(0.25)
    Q3 = House_Pricing_cleaned[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    House_Pricing_cleaned = House_Pricing_cleaned[
        (House_Pricing_cleaned [col] >= lower_bound) &
        (House_Pricing_cleaned [col] <= upper_bound)
    ]

# Dataset size comparison
print("Original shape:", house_priced.shape)
print("After outlier removal:", House_Pricing_cleaned.shape)

Original shape: (21613, 21)
After outlier removal: (17259, 21)

#Scaling Numerical Variables

In [ ]:
from sklearn.preprocessing import StandardScaler

# Step 1: Identify numerical features (exclude target)
num_features = [
    col for col in House_Pricing_cleaned.columns
    if col != "Sale Price" and House_Pricing_cleaned[col].dtype in ["int64", "float64"]
]

print("Numerical features to scale:")
print(num_features)

# Step 2: Apply Standard Scaling
scaler = StandardScaler()

House_Pricing_cleaned[num_features] = scaler.fit_transform(
    House_Pricing_cleaned[num_features]
)

print("Scaling completed successfully")

Numerical features to scale:
['ID', 'No of Bedrooms', 'No of Bathrooms', 'Flat Area (in Sqft)', 'Lot Area (in Sqft)', 'No of Floors', 'Overall Grade', 'Area of the House from Basement (in Sqft)', 'Basement Area (in Sqft)', 'Age of House (in Years)', 'Renovated Year', 'Zipcode', 'Latitude', 'Longitude', 'Living Area after Renovation (in Sqft)', 'Lot Area after Renovation (in Sqft)']
Scaling completed successfully

In [ ]:
num_feature = [
    col for col in House_Pricing_cleaned.columns
    if col != "Sale Price" and House_Pricing_cleaned[col].dtype in ["int64", "float64"]
]

# Apply Standard Scaling
standard_scaler = StandardScaler()
House_Pricing_cleaned[num_features] = standard_scaler.fit_transform(
    House_Pricing_cleaned[num_features]
)
print("Standard scaling applied successfully")

House_Pricing_cleaned[num_feature].head()

Standard scaling applied successfully

,ID,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,0.826002,-0.315192,-1.461759,-1.020734,-0.402195,-0.858393,-0.446000,-0.671677,-0.666700,0.479182,-0.192703,1.766351,-0.358519,-0.187075,-0.920342,-0.411281
1,0.576894,-0.315192,0.369658,1.081912,0.091658,0.977078,-0.446000,0.919427,0.371512,0.612294,5.175781,0.785366,1.157616,-0.661605,-0.239386,0.291523
2,0.304311,-1.416833,-1.461759,-1.640939,0.947216,-0.858393,-1.542667,-1.330619,-0.666700,1.211295,-0.192703,-1.010021,1.279746,-0.003386,1.764569,0.440988
3,-0.790866,0.786449,1.468508,0.159168,-0.603831,-0.858393,-0.446000,-0.880610,1.695232,0.146404,-0.192703,0.988967,-0.289144,-1.227979,-0.881430,-0.640955
4,-0.976443,-0.315192,0.003374,-0.264387,0.351614,-0.858393,0.650667,0.131911,-0.666700,-0.585709,-0.192703,-0.158600,0.404607,1.435510,-0.025372,0.243468

#Encoding Categorical Variables

In [ ]:
#Identify all categorical columns in the dataset.
categ_col = House_Pricing_cleaned.select_dtypes(include=["object"]).columns
print(categ_col)

Index(['Date House was Sold', 'Waterfront View', 'No of Times Visited',
       'Condition of the House'],
      dtype='object')

In [ ]:
#numerical columns
nume_col = House_Pricing_cleaned.select_dtypes(include = ["int64","float64"]).columns
print(nume_col)

Index(['ID', 'Sale Price', 'No of Bedrooms', 'No of Bathrooms',
       'Flat Area (in Sqft)', 'Lot Area (in Sqft)', 'No of Floors',
       'Overall Grade', 'Area of the House from Basement (in Sqft)',
       'Basement Area (in Sqft)', 'Age of House (in Years)', 'Renovated Year',
       'Zipcode', 'Latitude', 'Longitude',
       'Living Area after Renovation (in Sqft)',
       'Lot Area after Renovation (in Sqft)'],
      dtype='object')

In [ ]:
# Apply appropriate encoding techniques:
# Use One-Hot Encoding for nominal categories.
House_Pricing_encoded = pd.get_dummies(House_Pricing_cleaned,columns=categ_col,drop_first=True,dtype = int)
House_Pricing_encoded.head()

,ID,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),...,Date House was Sold_15 March 2016,Date House was Sold_15 May 2016,Waterfront View_Yes,No of Times Visited_Once,No of Times Visited_Thrice,No of Times Visited_Twice,Condition of the House_Excellent,Condition of the House_Fair,Condition of the House_Good,Condition of the House_Okay
0,0.826002,221900.0,-0.315192,-1.461759,-1.020734,-0.402195,-0.858393,-0.446000,-0.671677,-0.666700,...,0,0,0,0,0,1,0,1,0,0
1,0.576894,538000.0,-0.315192,0.369658,1.081912,0.091658,0.977078,-0.446000,0.919427,0.371512,...,0,0,0,0,0,1,0,1,0,0
2,0.304311,180000.0,-1.416833,-1.461759,-1.640939,0.947216,-0.858393,-1.542667,-1.330619,-0.666700,...,0,0,0,0,0,1,0,1,0,0
3,-0.790866,604000.0,0.786449,1.468508,0.159168,-0.603831,-0.858393,-0.446000,-0.880610,1.695232,...,0,0,0,0,0,1,1,0,0,0
4,-0.976443,510000.0,-0.315192,0.003374,-0.264387,0.351614,-0.858393,0.650667,0.131911,-0.666700,...,0,0,0,0,0,1,0,1,0,0

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Identify ordinal categorical columns (NONE in this dataset)
ordinal_cols = []   # No ordinal categorical features

if len(ordinal_cols) > 0:
    le = LabelEncoder()
    for col in ordinal_cols:
        House_Pricing_cleaned[col] = le.fit_transform(House_Pricing_cleaned[col])
    print("Label encoding applied on ordinal columns")
else:
    print("No ordinal categorical columns found. Label encoding not applied.")

No ordinal categorical columns found. Label encoding not applied.

#Train-Test Split

In [ ]:
# Set aside the SalePrice column as the target variable.
# Split the dataset into training (80%) and testing (20%) sets using the train_test_split function from sklearn.

from sklearn.model_selection import train_test_split

# 1. Set target variable
X = House_Pricing_cleaned.drop("Sale Price", axis=1)
y = House_Pricing_cleaned["Sale Price"]

# 2. Split into training and testing sets (80% / 20%)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 3. Check shapes
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (13807, 20)
X_test shape: (3452, 20)
y_train shape: (13807,)
y_test shape: (3452,)